
# Este programa cuenta chistes
print('¿que sale de la cruza entre un mono y un pato?')
input()
print('¡un monopatín!')
print()
print('¿por que los pajaros vuelan pa\'l sur?')
input()
print('¡por que caminando tardarian muchisimo!')
print()
print('¿en que se parecen una familia, un bombero y un barco?')
input()
print('no se.... ¿en que se parecen?')
input()
print('en que el bombero y el barco tienen casco.')
input()
print ('¿y la familia?', end='')
print('-Bien, gracias.')